test_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_panel.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_panel/urls.py
from django.urls import path
from user_panel.views import (
	CategoryView,Dashboard,
	CategorySubcategoryMaster,edit_category_sub_category
	)

app_name = "user_panel"

urlpatterns = [
	path('api/category/',CategoryView.as_view(),name="category"),
	path('api/category/<id>/',CategoryView.as_view(),name="category"),
	path('dashboard/',Dashboard.as_view(),name="dashboard"),
	path('create_category/',CategorySubcategoryMaster.as_view(),name="create_category"),
	path('edit_cat_sub_cat/',edit_category_sub_category,name="edit_cat_sub_cat"),
]

user_panel/models.py
from django.db import models
from django.contrib.auth.models import User

class CategorySubcategory(models.Model):
	created_by = models.ForeignKey(User,on_delete=models.CASCADE)
	name = models.CharField(max_length=200,blank=True)
	category_id = models.PositiveIntegerField(blank=True,null=True)
	def __str__(self):
		return self.name

class Product(models.Model):
	created_by = models.ForeignKey(User,on_delete=models.CASCADE)
	category = models.ManyToManyField(CategorySubcategory)
	name = models.CharField(max_length=200,blank=True)
	price = models.PositiveIntegerField(blank=True)

	def __str__(self):
		return self.name

user_panel/forms.py
from django.forms import ModelForm
from django import forms
from user_panel.models import (
	CategorySubcategory,Product
    )

class CategorySubcategorymasterForm(ModelForm):
    class Meta:
        model =CategorySubcategory
        fields = "__all__"
        exclude = ['id','created_by','category_id']
    name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control'}))



class CategorySubcategoryUpdateForm(ModelForm):
    class Meta:
        model =CategorySubcategory
        fields = "__all__"
        exclude = ['id','created_by']
    name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control'}))


 

user_panel/views.py
from django.shortcuts import render
from rest_framework import status
from rest_framework import generics
from rest_framework import mixins
from user_panel.serializers import ProductSerializer,CategorySerializer
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication,BasicAuthentication 
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from django_filters.rest_framework import DjangoFilterBackend
from user_panel.models import CategorySubcategory,Product
from django.views.generic import TemplateView,CreateView
from user_panel.forms import CategorySubcategorymasterForm,CategorySubcategoryUpdateForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponse,JsonResponse
class CategoryView(
	generics.GenericAPIView,
	mixins.ListModelMixin,
	mixins.RetrieveModelMixin,
	mixins.CreateModelMixin,
	mixins.UpdateModelMixin,
	mixins.DestroyModelMixin):

	serializer_class = CategorySerializer
	queryset = CategorySubcategory.objects.all()
	lookup_field = 'id'
	authentication_classes = [SessionAuthentication,BasicAuthentication]
	#permission_classes =[IsAuthenticated]
	def get(self,request,id=None):
		if id:
			return self.retrieve(request,id)
		else:
			return self.list(request)

	@permission_classes([IsAuthenticated])
	def post(self,request,id=None):
		return self.create(request)

	@permission_classes([IsAuthenticated])
	def put(self,request,id=None):
		return self.update(request,id)
	@permission_classes([IsAuthenticated])
	def delete(self,request,id=None):
		return self.destroy(request,id)

@method_decorator(login_required, name='dispatch')
class Dashboard(TemplateView):
	template_name = "base.html"

@method_decorator(login_required, name='dispatch')
class CategorySubcategoryMaster(CreateView):
    model = CategorySubcategory
    form_class = CategorySubcategorymasterForm
    template_name = "category/create.html"
    success_url = "/create_category/"
    def post(self,request,*args,**kwargs):
        form = CategorySubcategorymasterForm(self.request.POST)
        if form.is_valid():
            form.instance.created_by = self.request.user
            cat_type = request.POST.get('optradio')
            if cat_type == 'category':
                 form.instance.save()
                 return redirect(self.success_url)
            else:
                title = request.POST.get('name')
                cat_id = request.POST.getlist('name')
                for i in cat_id:
                    CategorySubcategory.objects.create(created_by = self.request.user,title = title,category_id = i)  
                else:
                    print("Broken For loop")
                return redirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(**kwargs)
        dictionary = []
        data = CategorySubcategory.objects.filter(category_id__isnull=True).values('id','name')
        for i in data:
            title = i['name']
            cat_id = i['id']
            dictionary.append({"category":title,"id":cat_id, "sub_category":CategorySubcategory.objects.filter(category_id=cat_id).values('id','name')})
        #print("***************************************",context)
        context['category'] = CategorySubcategory.objects.filter(category_id__isnull=True).values('id','name')
        #print("*******************",dictionary)
        context.update({'data': dictionary})
        return context

@login_required
def edit_category_sub_category(request):
	if request.metho=='POST':
		print("/*/*/*/",request.GET.get('cat_id'))
		data = CategorySubcategory.objects.filter(id=request.GET.get('cat_id')).update()
		return JsonResponse(list(data),safe=False)
	else:
		print("/*/*/*/",request.GET.get('cat_id'))
		data = CategorySubcategory.objects.filter(id=request.GET.get('cat_id')).values()
		return JsonResponse(list(data),safe=False)
	

templates/category/create.html
{% extends 'base.html' %}


{% load static %}

{% block heading %} <h3 class="page-title"></h3> {% endblock heading %}
{% block dashboard_thumbs %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="col-md-6 offset-3">

 <h3 class="page-title">Add Category</h3>  
        <div class="card">
        <form method="POST" enctype="multipart-form-data">{% csrf_token %}
   
  <div class="form-check-inline offset-2">
      <label class="form-check-label" for="radio1">
        <input type="radio" class="form-check-input" id="radio1" data-subcatId="" name="optradio" value="category" checked>Category
      </label>
    </div>

    <div class="form-check-inline offset-2" >
      <label class="form-check-label" for="radio2">
        <input type="radio" class="form-check-input" id="radio2" name="optradio" value="subcategory">Sub Category
      </label>
    </div>
<br>


{{ form.as_p }}

<div class="category">
<label for="id_sub_cat" style="display: none;">Category:</label>
<select class="selectpicker form-control" name="titles" id="sub_cat" multiple data-live-search="true">

{% for i in category %}

  <option value="{{ i.id }}"><h1>{{ i.title }}</h1></option>
 
{% endfor %} 


</select>
</div>
{% comment %} <br>
{% for i in category %}
  <input type="hidden" name="get_cat_id" value="{{ i.id }}">
{% endfor %}  {% endcomment %}

<input class="btn btn-info" type="submit" value="submit">
</form>

    </div>
</div>




<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
         
          <h4 class="modal-title text-center">Update Category & Subcategory </h4>
        </div>
        

        <div class="modal-body">
          
      <form method="POST" action="{% url 'user_panel:edit_cat_sub_cat' %}" enctype="multipart-form-data">{% csrf_token %}
          <div id="showFields">
            </div>
          <input type="submit" class="btn btn-default" value="Submit">
      </form>
        


        </div>
       
      </div>
      
    </div>
  </div>





<div class="container">
    <div class="card-body">
      <h2 align="center">Added Categories & Sub Categories</h2>

    <div class="row">
        <div class="col-md-6 offset-md-3"> 
              <table class="table table-dark">
            
            <thead>
              <tr>
                <th>Id</th>
                <th>Category </th>
                <th>Sub Category </th>
                <th>Action </th>
              </tr>
            </thead> 
       <tbody>
    


          {% for i in data %}
              <tr>          
                <td>{{ forloop.counter }}</td>
                 <td>{{ i.category }}</td>
                 
                <td> {% for j in i.sub_category  %} <i class="fa fa-circle"style="font-size:8px"></i> {{ j.title }}  {% endfor %}</td>
                <td><a href="#" class="btn btn-info editCat" data-toggle="modal" data-target="#myModal"  data-catId="{{ i.id }}" ><i class="fa fa-pencil" aria-hidden="true" style="color:white;"></i> </a></td>
              </tr>
             
          {% endfor %}   
      </tbody>
    </table>
  </div>





</div>
</div> 
</div>




<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>



   
$(document).ready(function(){
 $('#sub_cat').hide();

 
    $("input[type$='radio']").click(function() {
        var test = $(this).val();
        //console.log(test);
        if(test == 'subcategory') {
            $('.category').show();
            $('#sub_cat').select2();
            //$('#sub_cat option:selected').
            //var subcatName = $('#sub_cat').data('catName');
            //console.log(subcatName); //return false;
            //$('#id_title').hide();
            //$('label[for=id_title], input#id_title').hide(); 
            $('label[for=id_sub_cat], input#id_sub_cat').show(); 
        }else{
             $('#sub_cat .selectpicker').hide();
             $('label[for=id_sub_cat], input#id_sub_cat').hide(); 
             $('#id_title').show();
             $('label[for=id_title], input#id_title').show(); 
             $('.category').hide(); 
        }

    });



    $("input[type='radio']").click(function(){
        var radioValue = $("input[name='optradio']:checked").val();

        if(radioValue){
           // alert("Your selected - " + radioValue);
        }

       //console.log(categoryId); return false;
        window.CSRF_TOKEN = "{{ csrf_token }}";
        //console.log(lebalId); return false;
        if(radioValue) {
            $.ajax({
                url:'/get_category/',
                type:'POST',
                //dataType:'json',
                
                data:{
                    'radiovalue': radioValue,
                    

                    csrfmiddlewaretoken: window.CSRF_TOKEN
                    
                },

                success : function(data){
                    console.log("/*/*/*/*/*/",data);
                var optionstr='',data;
                //data = jQuery.parseJSON(data);
                if($.isEmptyObject(data)){
                
                    optionstr+='<option value=0>'+"No Value Assigned"+ '</option>' ;
                }else {
                    $.each(data,function(key,value) { console.log(key,value);

                        
                        optionstr+='<option value='+value.id+'>'+value.name+ '</option>' ;
                    });
                }
                var dd = ' <select class="selectpicker w-100 form-control" multiple id="id_attribute_name" name="name[]">'+optionstr+'</select>';
                $('#showattr').html(dd);
                }    

                
                //alert(value.fields.label_value+value.pk);
            }); 
        }
    });


    });
</script>


<script>
// Editing Category and Sub Category //

$('.editCat').click(function(){

    var cat_id = $(this).attr('data-catId');
    //alert(cat_id);

    $.ajax
    ({ 
        url: '/edit_cat_sub_cat/',
        data: {"cat_id": cat_id},
        type: 'GET',
        dataType:'json',
        success: function(data)
        {
          console.log(data);

           var dd = '';//data
           $.each(data,function(key,val){
           	console.log("/*/*//*/*",val)
             dd += (key+1)+') '+'<input type="text" id="Cat_'+val['id']+'" name="cat" value="'+val['name']+'"><br/><br/>'+'<input type="hidden"  name="cat_id" value="'+val['id']+'"><br/><br/>'

              
             
           });

          $('#myModal').show();
          $('#showFields').html(dd);
 
        }
    });
});
</script>







{% endblock dashboard_thumbs %}